modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="dark_vs_light"
version="0.4.0"
displayName="Dark Vs Light"
credits="Credits to Gaurdian for being my tester Thanks to myuu for the music  https://www.youtube.com/channel/UCiSKnkKCKAQVxMUWpZQobuQ and https://www.FesliyanStudios.com"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dark-vs-light"
logoFile="logo.png"
authors="BoogaEye"
description='''
Darkness has taken over. watch out......
'''

[[dependencies.dark_vs_light]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




