modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="dark_v_light"
version="0.0.1"
displayName="Dark V Light"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="BoogaEye"

[[dependencies.dark_v_light]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




