/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.boogaeye.darkvlight;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class DarkVsLightModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public DarkVsLightModElements() {
		sounds.put(new ResourceLocation("dark_vs_light", "upgrade"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "upgrade")));
		sounds.put(new ResourceLocation("dark_vs_light", "dstonebreak"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "dstonebreak")));
		sounds.put(new ResourceLocation("dark_vs_light", "trader"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "trader")));
		sounds.put(new ResourceLocation("dark_vs_light", "darkendtallend"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "darkendtallend")));
		sounds.put(new ResourceLocation("dark_vs_light", "darkendtallendhurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "darkendtallendhurt")));
		sounds.put(new ResourceLocation("dark_vs_light", "tracker"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "tracker")));
		sounds.put(new ResourceLocation("dark_vs_light", "trackercrafted"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "trackercrafted")));
		sounds.put(new ResourceLocation("dark_vs_light", "trackerdeny"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "trackerdeny")));
		sounds.put(new ResourceLocation("dark_vs_light", "trackerdrop"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "trackerdrop")));
		sounds.put(new ResourceLocation("dark_vs_light", "trackerfound"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "trackerfound")));
		sounds.put(new ResourceLocation("dark_vs_light", "bosshurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "bosshurt")));
		sounds.put(new ResourceLocation("dark_vs_light", "bossidle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "bossidle")));
		sounds.put(new ResourceLocation("dark_vs_light", "bossspell"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "bossspell")));
		sounds.put(new ResourceLocation("dark_vs_light", "bosswalk"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "bosswalk")));
		sounds.put(new ResourceLocation("dark_vs_light", "waterfill"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "waterfill")));
		sounds.put(new ResourceLocation("dark_vs_light", "hornstomp"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "hornstomp")));
		sounds.put(new ResourceLocation("dark_vs_light", "hornambient"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "hornambient")));
		sounds.put(new ResourceLocation("dark_vs_light", "hornhurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "hornhurt")));
		sounds.put(new ResourceLocation("dark_vs_light", "dloner"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "dloner")));
		sounds.put(new ResourceLocation("dark_vs_light", "dlonerhurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "dlonerhurt")));
		sounds.put(new ResourceLocation("dark_vs_light", "darkendwolfam"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "darkendwolfam")));
		sounds.put(new ResourceLocation("dark_vs_light", "darkenddessertambient"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "darkenddessertambient")));
		sounds.put(new ResourceLocation("dark_vs_light", "dfloater"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "dfloater")));
		sounds.put(new ResourceLocation("dark_vs_light", "dfloaterhurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "dfloaterhurt")));
		sounds.put(new ResourceLocation("dark_vs_light", "bdiamond"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "bdiamond")));
		sounds.put(new ResourceLocation("dark_vs_light", "shadowarmor"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "shadowarmor")));
		sounds.put(new ResourceLocation("dark_vs_light", "burngazeforest"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "burngazeforest")));
		sounds.put(new ResourceLocation("dark_vs_light", "blindforest"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "blindforest")));
		sounds.put(new ResourceLocation("dark_vs_light", "hornsong"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "hornsong")));
		sounds.put(new ResourceLocation("dark_vs_light", "drag"), new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "drag")));
		sounds.put(new ResourceLocation("dark_vs_light", "burnforestambient"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "burnforestambient")));
		sounds.put(new ResourceLocation("dark_vs_light", "burngazeadditions"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "burngazeadditions")));
		sounds.put(new ResourceLocation("dark_vs_light", "burnforestmood"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "burnforestmood")));
		sounds.put(new ResourceLocation("dark_vs_light", "enlightendspider"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "enlightendspider")));
		sounds.put(new ResourceLocation("dark_vs_light", "enchantedloop"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "enchantedloop")));
		sounds.put(new ResourceLocation("dark_vs_light", "enlightendspiderhurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "enlightendspiderhurt")));
		sounds.put(new ResourceLocation("dark_vs_light", "hololoop"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "hololoop")));
		sounds.put(new ResourceLocation("dark_vs_light", "darkforest"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "darkforest")));
		sounds.put(new ResourceLocation("dark_vs_light", "apocalypse"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "apocalypse")));
		sounds.put(new ResourceLocation("dark_vs_light", "theswamp"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "theswamp")));
		sounds.put(new ResourceLocation("dark_vs_light", "lovehim"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "lovehim")));
		sounds.put(new ResourceLocation("dark_vs_light", "oceanending"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "oceanending")));
		sounds.put(new ResourceLocation("dark_vs_light", "breakdarkgrass"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "breakdarkgrass")));
		sounds.put(new ResourceLocation("dark_vs_light", "upgradestart"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "upgradestart")));
		sounds.put(new ResourceLocation("dark_vs_light", "upgradeloop"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "upgradeloop")));
		sounds.put(new ResourceLocation("dark_vs_light", "upgradeend"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "upgradeend")));
		sounds.put(new ResourceLocation("dark_vs_light", "deepdark"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "deepdark")));
		sounds.put(new ResourceLocation("dark_vs_light", "disintegrating"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "disintegrating")));
		sounds.put(new ResourceLocation("dark_vs_light", "dessert"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "dessert")));
		sounds.put(new ResourceLocation("dark_vs_light", "randomdark"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "randomdark")));
		sounds.put(new ResourceLocation("dark_vs_light", "dgrassbreak"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("dark_vs_light", "dgrassbreak")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("dark_vs_light").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == DarkVsLightModElements.ModElement.class)
						elements.add((DarkVsLightModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(DarkVsLightModElements.ModElement::initElements);
		MinecraftForge.EVENT_BUS.register(new DarkVsLightModVariables(this));
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}
	private int messageID = 0;
	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		DarkVsLightMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final DarkVsLightModElements elements;
		protected final int sortid;
		public ModElement(DarkVsLightModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
